### ISSUE TITLE
What pretrained model is used to generate the global feature?

### ISSUE THREAD

**Issue by squareRoot3** [luoyunan/ECNet#7]
ECNet uses Type-Protein to encode global features but does not specify any pretrained weights to initialize the Transformer (`from_pretrained=None'). If so, the global features seem to be generated by a randomly initialized Transformer encoder.

**Comment by luoyunan** [comment]
Thanks for reporting the issue. TAPE now provides auto-downloading option which does not require specifying the path to the pretrained weights. We did not set the argument correctly when release the GitHub code. This issue has been fixed in https://github.com/luoyunan/ECNet/commit/a8c3cc754306578761c9ef030c9c5eef0cb29496. You don't need to pre-download the TAPE pretrained model before running ECNet -- it will be automatically downloaded to `~/.cache/torch/protein_models` if it is not there.

**Comment by squareRoot3** [comment]
I see. Thank you for your quick response!
